# Generated by Django 4.2.5 on 2023-10-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
